/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: 'var(--color-card)',
        'card-foreground': 'var(--color-card-foreground)',
        popover: 'var(--color-popover)',
        'popover-foreground': 'var(--color-popover-foreground)',
        primary: 'var(--color-primary)',
        'primary-foreground': 'var(--color-primary-foreground)',
        'primary-50': 'var(--color-primary-50)',
        'primary-100': 'var(--color-primary-100)',
        'primary-500': 'var(--color-primary-500)',
        'primary-600': 'var(--color-primary-600)',
        'primary-900': 'var(--color-primary-900)',
        secondary: 'var(--color-secondary)',
        'secondary-foreground': 'var(--color-secondary-foreground)',
        muted: 'var(--color-muted)',
        'muted-foreground': 'var(--color-muted-foreground)',
        accent: 'var(--color-accent)',
        'accent-foreground': 'var(--color-accent-foreground)',
        destructive: 'var(--color-destructive)',
        'destructive-foreground': 'var(--color-destructive-foreground)',
        success: 'var(--color-success)',
        'success-foreground': 'var(--color-success-foreground)',
        warning: 'var(--color-warning)',
        'warning-foreground': 'var(--color-warning-foreground)',
        info: 'var(--color-info)',
        'info-foreground': 'var(--color-info-foreground)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        'status-approved': 'var(--color-status-approved)',
        'status-pending': 'var(--color-status-pending)',
        'status-rejected': 'var(--color-status-rejected)',
        'status-draft': 'var(--color-status-draft)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-foreground': 'var(--color-sidebar-foreground)',
        'sidebar-primary': 'var(--color-sidebar-primary)',
        'sidebar-primary-foreground': 'var(--color-sidebar-primary-foreground)',
        'sidebar-accent': 'var(--color-sidebar-accent)',
        'sidebar-accent-foreground': 'var(--color-sidebar-accent-foreground)',
        'sidebar-border': 'var(--color-sidebar-border)',
        'sidebar-ring': 'var(--color-sidebar-ring)',
        'table-header': 'var(--color-table-header)',
        'table-header-foreground': 'var(--color-table-header-foreground)',
        
        // Enhanced semantic color scales
        'success-50': 'var(--color-success-50)',
        'success-100': 'var(--color-success-100)',
        'success-200': 'var(--color-success-200)',
        'success-300': 'var(--color-success-300)',
        'success-400': 'var(--color-success-400)',
        'success-600': 'var(--color-success-600)',
        'success-700': 'var(--color-success-700)',
        'success-800': 'var(--color-success-800)',
        'success-900': 'var(--color-success-900)',
        
        'warning-50': 'var(--color-warning-50)',
        'warning-100': 'var(--color-warning-100)',
        'warning-200': 'var(--color-warning-200)',
        'warning-300': 'var(--color-warning-300)',
        'warning-400': 'var(--color-warning-400)',
        'warning-600': 'var(--color-warning-600)',
        'warning-700': 'var(--color-warning-700)',
        'warning-800': 'var(--color-warning-800)',
        'warning-900': 'var(--color-warning-900)',
        
        'destructive-50': 'var(--color-destructive-50)',
        'destructive-100': 'var(--color-destructive-100)',
        'destructive-200': 'var(--color-destructive-200)',
        'destructive-300': 'var(--color-destructive-300)',
        'destructive-400': 'var(--color-destructive-400)',
        'destructive-600': 'var(--color-destructive-600)',
        'destructive-700': 'var(--color-destructive-700)',
        'destructive-800': 'var(--color-destructive-800)',
        'destructive-900': 'var(--color-destructive-900)',
        
        'info-50': 'var(--color-info-50)',
        'info-100': 'var(--color-info-100)',
        'info-200': 'var(--color-info-200)',
        'info-300': 'var(--color-info-300)',
        'info-400': 'var(--color-info-400)',
        'info-600': 'var(--color-info-600)',
        'info-700': 'var(--color-info-700)',
        'info-800': 'var(--color-info-800)',
        'info-900': 'var(--color-info-900)',
        
        'neutral-50': 'var(--color-neutral-50)',
        'neutral-100': 'var(--color-neutral-100)',
        'neutral-200': 'var(--color-neutral-200)',
        'neutral-300': 'var(--color-neutral-300)',
        'neutral-400': 'var(--color-neutral-400)',
        'neutral-500': 'var(--color-neutral-500)',
        'neutral-600': 'var(--color-neutral-600)',
        'neutral-700': 'var(--color-neutral-700)',
        'neutral-800': 'var(--color-neutral-800)',
        'neutral-900': 'var(--color-neutral-900)',
        
        // Enhanced status colors
        'status-approved': 'var(--color-status-approved)',
        'status-approved-bg': 'var(--color-status-approved-bg)',
        'status-approved-border': 'var(--color-status-approved-border)',
        'status-pending': 'var(--color-status-pending)',
        'status-pending-bg': 'var(--color-status-pending-bg)',
        'status-pending-border': 'var(--color-status-pending-border)',
        'status-rejected': 'var(--color-status-rejected)',
        'status-rejected-bg': 'var(--color-status-rejected-bg)',
        'status-rejected-border': 'var(--color-status-rejected-border)',
        'status-draft': 'var(--color-status-draft)',
        'status-draft-bg': 'var(--color-status-draft-bg)',
        'status-draft-border': 'var(--color-status-draft-border)',
        'status-submitted': 'var(--color-status-submitted)',
        'status-submitted-bg': 'var(--color-status-submitted-bg)',
        'status-submitted-border': 'var(--color-status-submitted-border)',
        
        // Enhanced card and elevated colors
        'card-elevated': 'var(--color-card-elevated)',
        'card-elevated-border': 'var(--color-card-elevated-border)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
}